baseURL = 'https://vincentrood.github.io/publicaties-Coevorden-test/'
languageCode = 'nl-nl'
title = 'PDF Zoekmachine'
theme = [] 

[taxonomies]
  map = "maps"

[params]
  s3_url = "https://publicaties-coevorden.s3.eu-north-1.amazonaws.com/"

[outputs]
  home = ["HTML", "Sitemap"]
  taxonomy = ["HTML", "XML"]
  term = ["XML"] # Dit genereert de XML per jaar, zonder een HTML pagina te maken
